version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=efomef62
  web:
    build: .
    command: gunicorn market.wsgi --bind 0.0.0.0:80
    volumes:
      - .:/src
    ports:
      - "80:80"
    environment:
      - POSTGRES_NAME=django_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=efomef62
    depends_on:
      - db
