# Generated by Django 4.0.5 on 2022-06-22 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('parentId', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[
                 ('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('parentId', models.CharField(blank=True, max_length=36, null=True)),
                ('type', models.CharField(choices=[
                 ('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
