# Generated by Django 4.0.5 on 2022-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunitstatistics',
            name='parentId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
